# Generated by Django 4.2.3 on 2024-04-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='username',
        ),
    ]
