# Generated by Django 4.2.3 on 2024-04-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_room_options_rename_host_room_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='username',
            new_name='host',
        ),
    ]
